version: "3"

services:
      
  petclinic:
    build: .
    image: petclinic:petProject
    restart: always
    ports:
      - 8050:8080
    environment:
      - MYSQL_ROOT_PASSWORD=senhadoroot
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
      - MYSQL_TCP_PORT=4407
    networks:
      - net-backend
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - 4407:4407
    environment:
      - MYSQL_ROOT_PASSWORD=senhadoroot
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
      - MYSQL_TCP_PORT=4407
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - net-backend

networks:
  net-backend:
